# Generated by Django 5.2.17 on 2026-09-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaNoResuelta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('mensaje_normalizado', models.CharField(db_index=True, max_length=500)),
                ('motivo', models.CharField(choices=[('sin_intencion', 'No se entendio la pregunta'), ('sin_datos', 'Se entendio, pero no hay datos'), ('persona_desconocida', 'Se nombro a alguien que no esta en la nomina'), ('persona_ambigua', 'El nombre coincide con varias personas')], default='sin_intencion', max_length=32)),
                ('veces', models.PositiveIntegerField(default=1)),
                ('primera_vez', models.DateTimeField(auto_now_add=True)),
                ('ultima_vez', models.DateTimeField(auto_now=True)),
                ('resuelta', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'consulta no resuelta',
                'verbose_name_plural': 'consultas no resueltas',
                'ordering': ['-veces', '-ultima_vez'],
            },
        ),
    ]
