# Generated by Django 5.2.17 on 2026-09-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('mensaje_normalizado', models.CharField(max_length=500, unique=True)),
                ('veces', models.PositiveIntegerField(default=1)),
                ('ultima_intencion', models.CharField(blank=True, max_length=32)),
                ('veces_modelo', models.PositiveIntegerField(default=0)),
                ('veces_cache', models.PositiveIntegerField(default=0)),
                ('primera_vez', models.DateTimeField(auto_now_add=True)),
                ('ultima_vez', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'preguntas',
                'ordering': ['-veces', '-ultima_vez'],
            },
        ),
    ]
