# Generated by Django 5.2.17 on 2026-09-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_pregunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultanoresuelta',
            name='motivo',
            field=models.CharField(choices=[('sin_intencion', 'No se entendio la pregunta'), ('sin_datos', 'Se entendio, pero no hay datos'), ('persona_desconocida', 'Se nombro a alguien que no esta en la nomina'), ('persona_ambigua', 'El nombre coincide con varias personas'), ('marcada_no_exitosa', 'El usuario marco la respuesta como no exitosa')], default='sin_intencion', max_length=32),
        ),
    ]
