# Generated by Django 5.2.17 on 2026-09-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_consultanoresuelta_motivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('pregunta', 'Pregunta que Iris debería poder responder'), ('mejora', 'Mejora o funcionalidad nueva'), ('otro', 'Otra idea')], default='mejora', max_length=16)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En progreso'), ('hecha', 'Hecha'), ('descartada', 'Descartada')], default='pendiente', max_length=16)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'propuesta',
                'verbose_name_plural': 'propuestas',
                'ordering': ['-creada_en'],
            },
        ),
    ]
