# Generated by Django 5.2.17 on 2026-09-10 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_propuesta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=254)),
                ('tipo', models.CharField(choices=[('injection', 'Posible inyección de prompt'), ('autz_denegada', 'Consulta fuera de alcance del rol'), ('rate_limit', 'Límite de frecuencia alcanzado'), ('presupuesto', 'Límite diario de consultas alcanzado'), ('entrada_larga', 'Consulta demasiado larga')], db_index=True, max_length=24)),
                ('detalle', models.CharField(blank=True, max_length=300)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'evento de seguridad',
                'verbose_name_plural': 'eventos de seguridad',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('gerencia', 'Gerencia — puede preguntar todo'), ('ejecutivo', 'Ejecutivo — acceso acotado a su jerarquía'), ('sin_acceso', 'Sin acceso — no puede usar el chat')], default='ejecutivo', max_length=16)),
                ('buk_employee_id', models.PositiveIntegerField(blank=True, null=True)),
                ('notas', models.CharField(blank=True, max_length=200)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil de usuario',
                'verbose_name_plural': 'perfiles de usuario',
                'ordering': ['usuario__email'],
            },
        ),
    ]
