# Generated by Django 5.2.17 on 2026-09-14 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_eventoseguridad_perfilusuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitacionRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rol', models.CharField(choices=[('gerencia', 'Gerencia — puede preguntar todo'), ('ejecutivo', 'Ejecutivo — acceso acotado a su jerarquía'), ('sin_acceso', 'Sin acceso — no puede usar el chat')], default='ejecutivo', max_length=16)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'invitación de rol',
                'verbose_name_plural': 'invitaciones de rol',
                'ordering': ['email'],
            },
        ),
    ]
