# Generated by Django 5.2.17 on 2026-09-16 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_invitacionrol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, db_index=True, max_length=254)),
                ('mensaje', models.TextField()),
                ('intencion', models.CharField(blank=True, max_length=32)),
                ('desde_cache', models.BooleanField(default=False)),
                ('ip', models.CharField(blank=True, max_length=64)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividad_chat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'actividad de chat',
                'verbose_name_plural': 'actividad de chat',
                'ordering': ['-creado_en'],
            },
        ),
    ]
