# Generated by Django 5.2.17 on 2026-09-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_actividadchat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitacionrol',
            name='rol',
            field=models.CharField(choices=[('gerencia', 'Gerencia — puede preguntar todo'), ('ejecutivo', 'Ejecutivo — acceso acotado a su jerarquía'), ('sin_acceso', 'Sin acceso — no puede usar el chat')], default='sin_acceso', max_length=16),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('gerencia', 'Gerencia — puede preguntar todo'), ('ejecutivo', 'Ejecutivo — acceso acotado a su jerarquía'), ('sin_acceso', 'Sin acceso — no puede usar el chat')], default='sin_acceso', max_length=16),
        ),
    ]
