# Generated by Django 5.2.17 on 2026-09-28 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_invitacionrol_rol_alter_perfilusuario_rol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buk_employee_id', models.PositiveIntegerField(unique=True)),
                ('departamento', models.CharField(choices=[('asuntos_publicos', 'Asuntos Públicos'), ('digital', 'Digital'), ('comunicaciones', 'Comunicaciones'), ('administracion', 'Administración')], max_length=32)),
                ('forma_trabajo', models.CharField(choices=[('permanente', 'Permanente'), ('hibrido', 'Híbrido'), ('transitorio', 'Transitorio')], max_length=16)),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('turno_1', 'Turno 1'), ('turno_2', 'Turno 2'), ('acuerdo', 'Acuerdo'), ('conciliacion_familiar', 'Conciliación familiar')], max_length=32)),
                ('observacion', models.TextField(blank=True, help_text='A qué corresponde el acuerdo o la conciliación familiar.')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'turno',
                'verbose_name_plural': 'turnos',
                'ordering': ['departamento', 'buk_employee_id'],
            },
        ),
    ]
