# Generated by Django 5.2.17 on 2026-09-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='numero_puesto',
            field=models.CharField(blank=True, help_text='El numero del puesto fisico, si tiene uno asignado.', max_length=10, verbose_name='N° de puesto'),
        ),
    ]
